version: 2
jobs:
  compilar:
    docker:
      - image: starefossen/ruby-node:2-8
    steps:
      - checkout
      - run:
          name: Instalando bundler
          command: gem install bundler
      - run: echo -e "Host trifulca.space\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: Subiendo a dokku
          command: make deploy_a_produccion
workflows:
  version: 2
  compilar:
    jobs:
      - compilar:
        filters:
          branches:
            only: master

